"""
This module defines the basic restaurant schema for the application.

Any updates to the restaurant details should follow this schema.
"""

from typing import List
from pydantic import BaseModel

# Menu Item Update model for input validation when updating menu item details.
class MenuItem_Update(BaseModel):
    id: int
    name: str
    price: float
    tags: List[str] = []

# Restaurant model
class Restaurant(BaseModel):
    id: int
    name: str
    city: str
    address: str
    manager_ids: List[str]  # List of user IDs who are managers of the restaurant

# Restaurant Create model for input validation when creating a new restaurant.
# This does not include the 'id' field since it is generated by the system.
# It also does not include the 'manager_ids' field since the only manager on creation is the logged in user.
class Restaurant_Create(BaseModel):
    name: str
    city: str
    address: str

# Restaurant Details Update model for input validation when updating restaurant details.
class Restaurant_Details_Update(BaseModel):
    id: int
    name: str 
    city: str
    address: str

# Restaurant Managers Update model for input validation when updating restaurant managers.
class Restaurant_Managers_Update(BaseModel):
    id: int
    manager_ids: List[str]
