"""
This module defines the basic restaurant schema for the application.
This includes the menu details as well.

Any updates to the restaurant details should follow this schema.
"""

from typing import List
from pydantic import BaseModel

# Menu item model
class MenuItem(BaseModel):
    id: int
    name: str
    price: float
    tags: List[str] = []  # Optional tags for the menu item (spicy, vegetarian, etc.)

# Menu Item Create model for input validation when creating a new menu item.
class MenuItem_Create(BaseModel):
    name: str
    price: float
    tags: List[str] = []

# Menu Item Update model for input validation when updating menu item details.
class MenuItem_Update(BaseModel):
    id: int
    name: str
    price: float
    tags: List[str] = []

# Menu Bulk Create model for input validation when adding multiple menu items to a restaurant's menu.
class MenuItem_Bulk_Create(BaseModel):
    items: List[MenuItem_Create] = []  # List of menu items to add to restaurant's menu.

# Menu Bulk Update model for input validation when updating multiple menu items in a restaurant's menu.
class MenuItem_Bulk_Update(BaseModel):
    items: List[MenuItem_Update] = []  # List of menu items to update in restaurant's menu.

# Restaurant model
# Each restaurant is associated with a single menu
class Restaurant(BaseModel):
    id: int
    name: str
    city: str
    address: str
    manager_ids: List[str]  # List of user IDs who are managers of the restaurant
    menu: List[MenuItem] = []

# Restaurant Create model for input validation when creating a new restaurant.
# This does not include the 'id' field since it is generated by the system.
# It also does not include the 'menu' field since it is created when the restaurant is created.
# It also does not include the 'manager_ids' field since the only manager on creation is the logged in user.
class Restaurant_Create(BaseModel):
    name: str
    city: str
    address: str
    menu: List[MenuItem_Create] = [] # Optional menu items when creating a restaurant

# Restaurant Details Update model for input validation when updating restaurant details.
class Restaurant_Details_Update(BaseModel):
    id: int
    name: str 
    city: str
    address: str

# Restaurant Managers Update model for input validation when updating restaurant managers.
class Restaurant_Managers_Update(BaseModel):
    id: int
    manager_ids: List[str]
