"""This module defines the basic user schema for the application.

Any updated to the users account details should follow this schema.
"""

from pydantic import BaseModel



# Base user model with common fields
class User(BaseModel):
    id: str
    email: str
    password: str
    reset_token: str | None = None  # Optional field for password reset token
    reset_token_expiry: int | None = None  # Optional field for token expiry timestamp

# user_create and user_update models for input validation.
# These do not include the 'id' field since it is generated by the system.
class User_Create(BaseModel):
    email: str
    password: str

class User_Update(BaseModel):
    email: str
    password: str

# password reset request model, for when a user forgets their password and needs to reset it.
class Password_Reset_Request(BaseModel):
    email: str

# password reset model, for when a user has forgotten their password and needs to reset it using a token.
class Password_Reset(BaseModel):
    new_password: str
    reset_token: str

# reset password model, when a logged in user wants to change their password.
class Password_Update_When_Logged_In(BaseModel):
    email: str
    old_password: str
    new_password: str