"""This module defines the basic user schema for the application.

Any updated to the users account details should follow this schema.
"""

from enum import Enum
from pydantic import BaseModel

# User role enumeration (for fixed set of roles)
class UserRole(str, Enum):
    CUSTOMER = "customer"
    RESTAURANT_MANAGER = "manager"
    ADMIN = "admin"
    DELIVERY_DRIVER = "driver"

# Base user model with common fields
class User(BaseModel):
    id: str
    email: str
    password: str
    age: int
    gender: str
    role: UserRole
    reset_token: str | None = None  # Optional field for password reset token
    reset_token_expiry: int | None = None  # Optional field for token expiry timestamp

# Specific user models
class Customer(User):
    role: UserRole = UserRole.CUSTOMER
    # we can extend this model with customer-specific properties in the future

class RestaurantManager(User):
    """Restaurant manager user type. Can be extended with manager-specific properties."""
    role: UserRole = UserRole.RESTAURANT_MANAGER
    # we can extend this model with manager-specific properties in the future

class Admin(User):
    """Admin user type. Can be extended with admin-specific properties."""
    role: UserRole = UserRole.ADMIN
    # we can extend this model with admin-specific properties in the future

class DeliveryDriver(User):
    """Delivery driver user type. Can be extended with driver-specific properties."""
    role: UserRole = UserRole.DELIVERY_DRIVER
    # we can extend this model with driver-specific properties in the future

# user_create and user_update models for input validation.
# These do not include the 'id' field since it is generated by the system.
class User_Create(BaseModel):
    email: str
    password: str
    name: str
    age: int
    gender: str
    role: UserRole

class User_Update(BaseModel):
    email: str
    password: str
    name: str
    age: int
    gender: str
    role: UserRole

# password reset request model, for when a user forgets their password and needs to reset it.
class Password_Reset_Request(BaseModel):
    email: str

# password reset model, for when a user has forgotten their password and needs to reset it using a token.
class Password_Reset(BaseModel):
    new_password: str
    reset_token: str

# reset password model, when a logged in user wants to change their password.
class Password_Update_When_Logged_In(BaseModel):
    email: str
    old_password: str
    new_password: str