name: Tests on Push (any branch)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r fullstack-project/backend/requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        git ls-files '*.py' | xargs -n 10 pylint || true
    - name: run pytest tests save coverage reports 
      run: |
        pytest fullstack-project/backend/testing
        pytest --cov=fullstack-project/backend/realtime \
          --cov-report=html:fullstack-project/backend/testing/coverage-reports-html/realtime
        pytest --cov=fullstack-project/backend/repositories \
          --cov-report=html:fullstack-project/backend/testing/coverage-reports-html/repositories
        pytest --cov=fullstack-project/backend/routers \
          --cov-report=html:fullstack-project/backend/testing/coverage-reports-html/routers
        pytest --cov=fullstack-project/backend/schemas \
          --cov-report=html:fullstack-project/backend/testing/coverage-reports-html/schemas
        pytest --cov=fullstack-project/backend/services \
          --cov-report=html:fullstack-project/backend/testing/coverage-reports-html/services
        pytest --cov=fullstack-project/backend/app \
          --cov-report=html:fullstack-project/backend/testing/coverage-reports-html/app
